import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLocalEnvironment } from './services/security/Environment.js';
import { GeminiProvider } from './services/ai/GeminiProvider.js';
import { GroqProvider } from './services/ai/GroqProvider.js';
import { LLMRouter } from './services/ai/LLMRouter.js';
import { LLMService } from './services/ai/LLMService.js';
import { QuotaManager } from './services/quota/QuotaManager.js';
import { UsageTracker } from './services/usage/UsageTracker.js';
import { FileSystemService } from './services/filesystem/FileSystemService.js';
import { TerminalManager } from './services/terminal/TerminalManager.js';
import { GitHubService } from './services/github/GitHubService.js';
import { PackageRegistryService } from './services/package-registry/PackageRegistryService.js';
import { AgentEventBus } from './services/events/AgentEventBus.js';
import { SecurityPolicy } from './services/security/SecurityPolicy.js';
import { SandboxManager } from './services/sandbox/SandboxManager.js';
import { CheckpointService } from './services/agent/CheckpointService.js';
import { ToolExecutor } from './services/agent/ToolExecutor.js';
import { AgentOrchestrator } from './services/agent/AgentOrchestrator.js';
import { PreviewManager } from './services/preview/PreviewManager.js';
import { DiagnosticLogger } from './services/security/DiagnosticLogger.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
loadLocalEnvironment(path.join(__dirname, '../..'));
const quotas = new QuotaManager({ AI_REQUESTS: Number(process.env.MAX_AI_REQUESTS_PER_DAY ?? 100), AI_TOKENS: Number(process.env.MAX_AI_TOKENS_PER_DAY ?? 100000), SANDBOX_MINUTES: Number(process.env.MAX_SANDBOX_MINUTES_PER_DAY ?? 30), GITHUB_REQUESTS: Number(process.env.MAX_GITHUB_REQUESTS_PER_DAY ?? 100), AGENT_ITERATIONS: Number(process.env.MAX_AGENT_ITERATIONS_PER_TASK ?? 10) });
const usage = new UsageTracker();
const llm = new LLMService(new LLMRouter({ gemini: new GeminiProvider(process.env.GEMINI_API_KEY), groq: new GroqProvider(process.env.GROQ_API_KEY) }, quotas, usage));
const fileSystem = new FileSystemService();
const terminals = new TerminalManager();
const github = new GitHubService(process.env.GITHUB_TOKEN);
const registries = new PackageRegistryService();
const preview = new PreviewManager();
const logger = new DiagnosticLogger(path.join(process.cwd(), '.ngola', 'logs'));
const events = new AgentEventBus();
const checkpoints = new CheckpointService();
const sandbox = new SandboxManager(quotas, { e2b: process.env.E2B_API_KEY, daytona: process.env.DAYTONA_API_KEY });
const approvals = new Map<string, (approved: boolean) => void>();
const security = new SecurityPolicy();
const orchestrator = new AgentOrchestrator(llm, events, new ToolExecutor(fileSystem, terminals, security, quotas, registries, github, sandbox, { workspace: process.cwd(), approve: (request) => new Promise((resolve) => { const approvalId = `${Date.now()}-${Math.random()}`; approvals.set(approvalId, resolve); events.emit('agent.approval_required', { approvalId, request }); }), onDiff: (diff) => events.emit('agent.diff', diff) }), checkpoints, Number(process.env.MAX_AGENT_ITERATIONS_PER_TASK ?? 10));
let mainWindow: BrowserWindow | undefined;

function createWindow(): void {
  mainWindow = new BrowserWindow({ width: 1440, height: 900, minWidth: 1100, minHeight: 700, backgroundColor: '#0b0d10', webPreferences: { preload: path.join(__dirname, '../preload/preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true } });
  if (process.env.NODE_ENV === 'development') mainWindow.loadURL('http://127.0.0.1:5173');
  else mainWindow.loadFile(path.join(__dirname, '../../dist/index.html'));
}

ipcMain.handle('app:get-config-status', () => ({ gemini: Boolean(process.env.GEMINI_API_KEY), groq: Boolean(process.env.GROQ_API_KEY), github: github.isConfigured(), sandbox: Boolean(process.env.E2B_API_KEY || process.env.DAYTONA_API_KEY) }));
ipcMain.handle('app:get-provider-status', () => { const today = usage.today(); const status = (configured: boolean, provider: string) => { const records = today.filter((record) => record.provider === provider); const last = records.at(-1); return { configured, requests: records.reduce((total, record) => total + record.requestCount, 0), lastUsed: last?.timestamp ?? null, error: null }; }; return { gemini: status(Boolean(process.env.GEMINI_API_KEY), 'gemini'), groq: status(Boolean(process.env.GROQ_API_KEY), 'groq'), github: status(github.isConfigured(), 'github'), e2b: status(Boolean(process.env.E2B_API_KEY), 'e2b'), daytona: status(Boolean(process.env.DAYTONA_API_KEY), 'daytona'), supabase: status(Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL), 'supabase') }; });
ipcMain.handle('quota:get', () => quotas.all());
ipcMain.handle('usage:get-today', () => usage.today());
ipcMain.handle('usage:clear', () => usage.clear());
ipcMain.handle('llm:generate', (_event, request, options) => llm.generate(request, options));
ipcMain.handle('fs:read', (_event, filePath: string) => fileSystem.read(filePath));
ipcMain.handle('fs:write', (_event, filePath: string, content: string) => fileSystem.write(filePath, content));
ipcMain.handle('fs:create', (_event, filePath: string, content?: string) => fileSystem.create(filePath, content));
ipcMain.handle('fs:mkdir', (_event, directory: string) => fileSystem.mkdir(directory));
ipcMain.handle('fs:rename', (_event, source: string, destination: string) => fileSystem.rename(source, destination));
ipcMain.handle('fs:copy', (_event, source: string, destination: string) => fileSystem.copy(source, destination));
ipcMain.handle('fs:move', (_event, source: string, destination: string) => fileSystem.move(source, destination));
ipcMain.handle('fs:delete', (_event, filePath: string) => fileSystem.delete(filePath));
ipcMain.handle('fs:search', (_event, directory: string, query: string) => fileSystem.search(directory, query));
ipcMain.handle('terminal:start', (_event, command: string, cwd: string) => terminals.start(command, cwd, (event) => mainWindow?.webContents.send('terminal:event', event)));
ipcMain.handle('terminal:write', (_event, sessionId: string, input: string) => terminals.write(sessionId, input));
ipcMain.handle('terminal:kill', (_event, sessionId: string) => terminals.kill(sessionId));
ipcMain.handle('github:list-repositories', () => github.listRepositories());
ipcMain.handle('github:get-repository', (_event, owner: string, repo: string) => github.getRepository(owner, repo));
ipcMain.handle('github:search-repositories', (_event, query: string) => github.searchRepositories(query));
ipcMain.handle('github:search-code', (_event, query: string) => github.searchCode(query));
ipcMain.handle('registry:search', (_event, registry: 'npm' | 'pypi', query: string) => registries.searchPackage(registry, query));
ipcMain.handle('registry:get', (_event, registry: 'npm' | 'pypi', name: string) => registries.getPackage(registry, name));
ipcMain.handle('registry:versions', (_event, registry: 'npm' | 'pypi', name: string) => registries.getVersions(registry, name));
ipcMain.handle('agent:start', (_event, request: string, workspace: string) => orchestrator.run(request, workspace));
ipcMain.handle('agent:cancel', (_event, taskId: string) => orchestrator.cancel(taskId));
ipcMain.handle('agent:get', (_event, taskId: string) => orchestrator.get(taskId));
ipcMain.handle('agent:approve', (_event, approvalId: string, approved: boolean) => { const resolve = approvals.get(approvalId); if (!resolve) return false; approvals.delete(approvalId); resolve(approved); return true; });
ipcMain.handle('checkpoint:list', () => checkpoints.list());
ipcMain.handle('checkpoint:restore', (_event, id: string) => checkpoints.restore(id));
ipcMain.handle('preview:detect', () => preview.detect());
ipcMain.handle('preview:open', (_event, url: string) => preview.open(url));
ipcMain.handle('diagnostic:log', (_event, message: string) => logger.info('renderer', { message }));
events.subscribe((event) => mainWindow?.webContents.send('agent:event', event));

app.whenReady().then(() => { createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
