import type { LLMService } from '../ai/LLMService.js';
import type { AgentEventBus } from '../events/AgentEventBus.js';
import type { AgentTaskPlan } from './AgentTool.js';
import { RequirementsAgent } from './RequirementsAgent.js';
import { ArchitectAgent } from './ArchitectAgent.js';
import { CoderAgent } from './CoderAgent.js';
import { TesterAgent } from './TesterAgent.js';
import { DebuggerAgent } from './DebuggerAgent.js';
import { ProjectMemory } from './ProjectMemory.js';
import { CheckpointService } from './CheckpointService.js';
import { ToolExecutor } from './ToolExecutor.js';

export interface AgentTaskState { id: string; request: string; workspace: string; status: 'running' | 'completed' | 'failed' | 'cancelled'; plan?: AgentTaskPlan; iterations: number; errors: string[]; startedAt: string; completedAt?: string; }
export class AgentOrchestrator { private readonly tasks = new Map<string, AgentTaskState>(); private cancelled = new Set<string>(); private readonly requirements: RequirementsAgent; private readonly architect: ArchitectAgent; private readonly coder: CoderAgent; private readonly tester = new TesterAgent(); private readonly debugger: DebuggerAgent; constructor(private readonly llm: LLMService, private readonly events: AgentEventBus, private readonly tools: ToolExecutor, private readonly checkpoints: CheckpointService, private readonly maxIterations = 10) { this.requirements = new RequirementsAgent(llm); this.architect = new ArchitectAgent(llm); this.coder = new CoderAgent(llm); this.debugger = new DebuggerAgent(llm); }
	async run(request: string, workspace: string): Promise<AgentTaskState> { const id = crypto.randomUUID(); const state: AgentTaskState = { id, request, workspace, status: 'running', iterations: 0, errors: [], startedAt: new Date().toISOString() }; this.tasks.set(id, state); const memory = new ProjectMemory(); this.events.emit('agent.started', { taskId: id, request }); try { this.events.emit('agent.planning', { taskId: id, message: 'Analisando pedido...' }); const requirements = await this.requirements.understand(request); memory.update({ goal: request, requirements }); const architecture = await this.architect.design(requirements); memory.update({ architecture }); const plan = this.createPlan(request); state.plan = plan; await this.checkpoints.create(workspace); this.events.emit('agent.reading_file', { taskId: id, message: 'Lendo package.json' }); const packageResult = await this.tools.execute({ name: 'read_file', input: { path: 'package.json' }, reason: 'entender scripts e dependências' }); const context = packageResult.ok ? String(packageResult.output) : ''; const suggestion = await this.coder.suggest(request, context); memory.addSolution(suggestion); while (state.iterations < this.maxIterations && !this.cancelled.has(id)) { state.iterations += 1; const command = this.tester.chooseCommand(context); this.events.emit('agent.testing', { taskId: id, message: `Executando ${command}` }); const result = await this.tools.execute({ name: 'run_command', input: { command, cwd: '.' }, reason: 'validar o estado real do projeto' }); const evidence = this.tester.result(result); if (evidence.passed) { plan.tasks[plan.tasks.length - 1].status = 'completed'; this.events.emit('agent.completed', { taskId: id, evidence: evidence.evidence }); state.status = 'completed'; break; } state.errors.push(evidence.evidence); this.events.emit('agent.error', { taskId: id, error: evidence.evidence }); this.events.emit('agent.fixing', { taskId: id, message: 'Analisando erro' }); await this.debugger.diagnose(evidence.evidence, context); }
		if (this.cancelled.has(id)) { state.status = 'cancelled'; this.events.emit('agent.cancelled', { taskId: id }); } else if (state.status === 'running') { state.status = 'failed'; this.events.emit('agent.error', { taskId: id, error: 'O agente atingiu o limite de iterações desta tarefa.' }); }
		} catch (error) { state.status = this.cancelled.has(id) ? 'cancelled' : 'failed'; state.errors.push(error instanceof Error ? error.message : String(error)); this.events.emit('agent.error', { taskId: id, error: state.errors.at(-1) }); } state.completedAt = new Date().toISOString(); return state; }
	cancel(taskId: string): void { this.cancelled.add(taskId); }
	get(taskId: string): AgentTaskState | undefined { return this.tasks.get(taskId); }
	private createPlan(request: string): AgentTaskPlan { return { goal: request, requirements: [request], architecture: [], stack: [], files: [], dependencies: [], tasks: [{ id: 'task-1', description: 'Entender e validar o estado atual do projeto', status: 'running', files: [], commands: [], errors: [], iterations: 0 }], tests: ['npm test', 'npm run build'] }; }
}
